version: '3.3'
services:
    php-fpm:
        build:
          context: ./php-fpm
          dockerfile: Dockerfile
        expose:
            - "9000"
        volumes:
            - ${VOL_CODE}:/var/www/html
            - ./php-fpm/www_pool.conf:/usr/local/etc/php-fpm.d/www_pool.conf
        restart: unless-stopped
    nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      volumes:
          - ${VOL_CODE}:/var/www/html/
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/sites-enabled/shorturl.conf:/etc/nginx/sites-enabled/shorturl.conf
      environment:
        - MYSQL_DATABASE=short_url_db
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=password
        - MYSQL_HOST=db
      ports:
        - "${WEB_PORTS}:8000"
      depends_on:
        - db
      restart: unless-stopped
    composer:
        build:
          context: composer/
        environment:
          - SSH_AUTH_SOCK=/ssh-auth.sock
        volumes:
          - "${VOL_CODE}:/app"
          - "$SSH_AUTH_SOCK:/ssh-auth.sock"
        command: ['composer', 'install']
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        build:
          context: ./mysql
          dockerfile: Dockerfile
        ports:
          - 13306:3306
        restart: always
        environment:
          - MYSQL_DATABASE=short_url_db
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=password
          - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./mysql/sql-scripts/:/docker-entrypoint-initdb.d/:rw
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./my-db:/var/lib/mysql/
        command: [ 'mysqld', '--character-set-server=utf8']
        # networks:
        # - default
volumes:
  my-db: { driver: local }

